BRANd_nAME_old = [
        ('ACER' , 'ACER'),
        ('ALCAEL' , 'ALCAEL'),
        ('ALLVIEW' , 'ALLVIEW'),
        ('AMAZON' , 'AMAZON'),
        ('AMOL' , 'ABOL'),
        ('APPLE' , 'APPLE'),
        ('ARCHOS' , 'ARCHOS'),
        ('ASUS' , 'ACUS'),
        ('ATGT' , 'ATGT'),
        ('BENFON' , 'BENFON'),
        ('BENQ' , 'BENQ'),
        ('BENQ SIEMENS' , 'BENQ SIMENS'),
        ('BIRD' , 'BIRD'),
        ('BLACKBERRY' , 'BLACKBERRY'),
        ('BLACKVIEW' , 'BLACKVIEW'),
        ('BLU' , 'BLU'),
        ('BOSCH' , 'BOSCH'),
        ('BQ' , 'BQ'),
        ('CASIO' , 'CASIO'),
        ('CAT' , 'CAT'),
        ('CELKON' , 'CELKON'),
        ('CHEA' , 'CHEA'),
        ('COOLPAD' , 'COOLPAD'),
        ('EMPORIA' , 'EMPORIA'),
        ('DELL' , 'DELL'),
        ('DOOGEE' , 'DOOGEE'),
        ('EMPORIA' , 'EMPORIA'),
        ('ENERGIZER' , 'ENERGIZER'),
        ('ERICSSON' , 'ERICSSON'),
        ('ETEN' , 'ETEN'),
        ('FAIRPHONE' , 'FAIRPHONE'),
        ('FUJTSU SIEMENS' , 'FUJTSU SIEMENS'),
        ('GARMIN ASUS' , 'GARMIN ASUS'),
        ('GIGABYTE' , 'GIGABYTE'),
        ('GIONEE' , 'GIOEE'),
        ('GOOGLE' , 'GOOGLE'),
        ('HAIER' , 'HAIER'),
        ('HONOR' , 'HONOR'),
        ('HP' , 'HP'),
        ('HTC' , 'HTC'),
        ('HUAWEI' , 'HUAWEI'),
        ('I MATE' , 'IMATE'),
        ('ICEMOBILE' , 'ICEMOBILE'),
        ('INFINIX' , 'INFINIX'),
        ('ICEMOBILE' , 'ICEMOBILE'),
        ('INFINIX' , 'INFINIX'),
        ('INNOSTREAM' , 'INNOSTREAM'),
        ('INQ' , 'INQ'),
        ('INTEX' , 'INTEX'),
        ('JOLLA' , 'JOLLA'),
        ('KARBONN' , 'KARBONN'),
        ('KYOCERA' , 'KYOCERA'),
        ('LAVA' , 'LAVA'),
        ('LEECO' , 'LEECO'),
        ('LENOVO' , 'LENOVO'),
        ('LG' , 'LG'),
        ('MAXON' , 'MAXON'),
        ('MAXWEST' , 'MAXWEST'),
        ('MEIZU' , 'MEIZU'),
        ('MICROMAX' , 'MICROMAX'),
        ('MICROSOFT' , 'MICROSOFT'),
        ('MITAC' , 'MITAC'),
        ('MITSUBISHI' , 'MITSUBISHI'),
        ('MODU' , 'MODU'),
        ('MOTOROLA' , 'MOTOROLA'),
        ('MWG' , 'MWG'),
        ('NEC' , 'NEC'),
        ('NEONODE' , 'NEONODE'),
        ('NIU' , 'NIU'),
        ('NOKIA' , 'NOKIA'),
        ('NOTHING' , 'NOTHING'),
        ('NVIDIA' , 'NVIDIA'),
        ('O2' , 'O2'),
        ('ONEPLUS' , 'ONEPLUS'),
        ('OPPO' , 'OPPO'),
        ('PALM' , 'PALM'),
        ('PANASONIC' , 'PANASONIC'),
        ('PANTECH' , 'PANTECH'),
        ('PARLA' , 'PARLA'),
        ('PHILIPS' , 'PHILIPS'),
        ('PLUM' , 'PLUM'),
        ('POSH' , 'POSH'),
        ('PRESTIGIO' , 'PRESTIGIO'),
        ('QMOBILE' , 'QMOBILE'),
        ('QTEK' , 'QTEK'),
        ('RAZER' , 'RAZER'),
        ('REALME' , 'REALME'),
        ('SAGEM' , 'SAGEM'),
        ('SAMSUNG' , 'SAMSUNG'),
        ('SENDO' , 'SENDO'),
        ('SEWON' , 'SEWON'),
        ('SHARP' , 'SHARP'),
        ('SIEMENS' , 'SIEMENS'),
        ('SONIM' , 'SONIM'),
        ('SONY' , 'SONY'),
        ('SONY ERICSSON' , 'SONY ERICSSON'),
        ('SPICE' , 'SPICE'),
        ('T-MOBILE' , 'T-MOBILE'),
        ('TCL' , 'TCL'),
        ('TECNO' , 'TECNO'),
        ('TEL.ME.' , 'TEL.ME.'),
        ('TELIT' , 'TELIT'),
        ('THURAYA' , 'THURAYA'),
        ('TOSHIBA' , 'TOSHIBA'),
        ('ULEFONE' , 'ULEFONE'),
        ('UNNECTO' , 'UNNECTO'),
        ('VERTU' , 'VERTU'),
        ('VERYKOOL' , 'VERYKOOL'),
        ('VIVO' , 'VIVO'),
        ('VK MOBILE' , 'VK MOBILE'),
        ('VODAFONE' , 'VODAFONE'),
        ('WIKO' , 'WIKO'),
        ('WND' , 'WND'),
        ('XIAOMI' , 'XIAOMI'),
        ('XOLO' , 'XOLO'),
        ('YEZZ' , 'YEZZ'),
        ('YOTA' , 'YOTA'),
        ('YU' , 'YU'),
        ('ZTE' , 'ZTE'),
    ]
brand_name = [
        ('Samsung' , 'Samsung'), #1
        ('Apple' , 'Apple'), #2
        ('Huawei' , 'Huawei'), #3
        ('Oppo' , 'Oppo'), #4
        ('xiaomi' , 'xiaomi'),
        ('Infinix' , 'Infinix'),
        ('Nokia' , 'Nokia'),
        ('Sony' , 'Sony'),
        ('LG' , 'LG'),
        ('HTC' , 'HTC'), #10
        ('Lenovo' , 'Lenovo'),
        ('Realme' , 'Realme'),
        ('Honor' , 'Honor'),
        ('ZTE' , 'ZTE'), #14
        ('Vivo' , 'Vivo'),
        ('Alcatel' , 'Alcatel'),
        ('Asus' , 'Asus'), #17
        ('Motorola' , 'Motorola'),
        ('Acer' , 'Acer'), #19
        ('Techno' , 'Techno'), #20
    ]

fault_tocustomer = [
    (' كسر بالشاشة او التاتش' , ' كسر بالشاشة او التاتش'),
    ('الشاشة او التاتش لا تعمل' , 'الشاشة او التاتش لا تعمل'),
    ('تفريغ سريع فى الشحن' , 'تفريغ سريع فى الشحن'),
    ('لا يظهر علامة الشحن' , 'لا يظهر علامة الشحن'),
    ('علامة الشحن تظهر ولكن الشحن لا يزيد' , 'علامة الشحن تظهر ولكن الشحن لا يزيد' ),
    ('الشحن يقل اثناء توصيل الشاحن' , 'الشحن يقل اثناء توصيل الشاحن'  ),
    ('يظهر علامة التعجب عند الشحن' , 'يظهر علامة التعجب عند الشحن' ),
    ('كسر بالشاشة' , 'كسر بالشاشة'),
    ('كسر بالتاتش' , 'كسر بالتاتش'),
    ('كسر بالشاشة والتاتش' , 'كسر بالشاشة والتاتش'),
    ('الشاشة لا تعمل' , 'الشاشة لا تعمل'),
    ('التاتش لا يعمل' , 'التاتش لا يعمل'),
    ('الجهاز لا يعمل' , 'الجهاز لا يعمل'),
    ('لا اسمع صوت الطرف الاخر فى المكالمات' , 'لا اسمع صوت الطرف الاخر فى المكالمات'),
    ('الطرف الاخر فى المكالمات لا يسمعنى' , 'الطرف الاخر فى المكالمات لا يسمعنى'),
    ('الجهاز بيهنج وبطئ فى الاستخدام' , 'الجهاز بيهنج وبطئ فى الاستخدام' ),
    ('الجهاز بطئ جدا ويتوقف فجأة عن العمل' , 'الجهاز بطئ جدا ويتوقف فجأة عن العمل' ),
    ('الجهاز بيرستر فجأة' , 'الجهاز بيرستر فجأة' ),
    ('عطل أخر' , 'عطل أخر' ),
    ]

spareparts = [
    ('DisplayScreen', 'DisplayScreen'),
    ('Lcd', 'Lcd'),
    ('Touch', 'Touch'),
    ('Board', 'Board'),
    ('Mic', 'Mic'),
    ('LoudSpeaker', 'LoudSpeaker'),
    ('EarSpeaker', 'EarSpeaker'),
    ('Ringer', 'Ringer'),
    ('ChargingJack', 'ChargingJack'),
    ('Button', 'Button'),
    ('InternalKeypad', 'InternalKeypad'),
    ('SubBoard', 'SubBoard'),
    ('MainCamera', 'MainCamera'),
    ('SelfieCamera', 'SelfieCamera'),
    ('Housing', 'Housing'),
    ('BackCover', 'BackCover'),
    ('HandfreeJack', 'HandfreeJack'),
    ('Vibrator', 'Vibrator'),
    ('Battery', 'Battery'),
    ('IC-Power', 'IC-Power'),
    ('IC-Charging', 'IC-Charging'),
    ('IC-Screendata', 'IC-Screendata'),
    ('Clean-Parts', 'Clean-Parts'),
    ('Antenna', 'Antenna'),
    ('Others', 'Others'),
    ]
#pdobjects = DataFrameManager()
quality_degree = [
    ('Master','Master'),
    ('TheSame','TheSame'),
    ('Copy','Copy'),
    ]

quality_category = [
    ('copy','copy'),
    ('highcopy','highcopy'),
    ('original','original(new)'),
    ('original(used)','original(used)'),
    ('original(changeglass)','original(changeglass)'),        
    ('other','other'),
    ]
area_list = (
    ('cute','cute'),
    ('miss ginger','miss ginger'),
    ('for u &  her','for u &  her'),
    ('put ring on it','put ring on it'),
    ('dany','dany'),
    ('angel','angel'),
)
city_list = (
    ('cairo','cairo'),
    ('alxandria','alxandria'),
    ('mansoura','mansoura'),
    ('por said','por said'),
    ('october','october'),
)
list_angineer =(
        ('ساره','ساره'),
        ('محمد','محمد'),
        ('محمود','محمود'),
        ('احمد','احمد'),
        ('عصام','عصام'),
        ('علي','علي'),
        ('اسماء','اسماء'),
        ('اسراء','اسراء'),
        ('عبدالله','عبد الله'),
)
type_of_user =(
        ('customer','customer'),
        ('tager','tager'),
        ('admin','admin'),
)